### ISSUE TITLE
Uploading image results in timeout (504)

### ISSUE THREAD

**Issue by Justin113D** [Piwigo/Piwigo#2175]
## Problem
I am running Piwigo using the Linuxserver provided docker image ( https://hub.docker.com/r/linuxserver/piwigo ) on my raspberry PI and am having trouble uploading images. Everything else runs perfectly fine.

## Details
I managed to successfully set up my Piwigo container, and am able to register, log in, create galleries & tags, view galleries and their contents, adjust configurations, install plugins etc. 

Everything works perfectly fine, but when I try to upload an image, the image gets successfully uploaded (and can be viewed in the gallery), but the server fails to respond to the upload POST request, until a timeout error is thrown.

The following line can be found in the nginx log after the 504 was received by the browser:
`[error] 255#255: *48 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.178.43, server: _, request: "POST /ws.php?method=pwg.images.upload&format=json HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.30:8081", referrer: "http://192.168.178.30:8081/admin.php?page=photos_add"`

I access the website directly via IPv4 address.

I already tried reaching out to the LinuxServer.io team, but they did not find the cause either, saying that this may be a Piwigo issue, and not a docker issue.

### System details
`Linux Justin-RASPI 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`

### Docker setup
Piwigo container:
```yaml
piwigo:
  image: lscr.io/linuxserver/piwigo
  restart: unless-stopped
  depends_on:
    - database
  networks:
    mainnet:
      ipv4_address: 172.20.1.5
  ports:
    - 8081:80
    - 8082:443
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Berlin
  volumes:
    - /srv/piwigo/config:/config
    - /mnt/ssd/server/piwigo:/gallery
```

Database container (for reference, if necessary)
```yaml
database:
  image: mariadb:lts
  restart: unless-stopped
  environment:
    - MARIADB_RANDOM_ROOT_PASSWORD=yes
  networks:
    mainnet:
      ipv4_address: 172.20.0.2
  ports:
    - "3306:3306"
  volumes:
    - /srv/database/backup:/backup
    - /srv/database/config:/etc/mysql
    - /srv/database/logs:/var/log/mysql
    - /srv/database/data:/var/lib/mysql
```

---
I am unfortunately not too knowledgeable with PHP, so I didn't try any debugging yet.

I'm thankful for every bit of help!
